resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604

variables:
  dummy: '42'
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Test*.csproj'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
