resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604

variables:
  dummy: '42'
steps:
- task: PythonScript@0
  displayName: 'Inject build number'
  inputs:
    scriptPath: deployment/build/patch-version.py
    arguments: 'AppInsights.TelemetryInitializers/AppInsights.TelemetryInitializers.csproj $(Build.BuildId)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Test*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration release'
- task: CopyFiles@2
  displayName: 'Copy Nuget packages to staging'
  inputs:
    SourceFolder: .
    Contents: '**/*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
