resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604

variables:
  dummy: '42'
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/*Test*.csproj'
- task: CopyFiles@2
  displayName: 'Copy Nuget packages to staging'
  inputs:
    SourceFolder: .
    Contents: '**/*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
